### ISSUE TITLE
TypeError: 'BoundArguments' object is not callable

### ISSUE THREAD

**Issue by KiddoZhu** [DeepGraphLearning/torchdrug#118]
The decorator `@utils.cached` causes the following error when evaluating [NBFNet](https://github.com/DeepGraphLearning/NBFNet)

```
Traceback (most recent call last):
  File "/home/b/bengioy/zhuzhaoc/nbfnet/script/run.py", line 66, in <module>
    test(cfg, solver)
  File "/home/b/bengioy/zhuzhaoc/nbfnet/script/run.py", line 44, in test
    solver.evaluate("valid")
  File "/home/b/bengioy/zhuzhaoc/.conda/envs/drug/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/gpfs/fs1/home/b/bengioy/zhuzhaoc/torchdrug/torchdrug/core/engine.py", line 206, in evaluate
    pred, target = model.predict_and_target(batch)
  File "/gpfs/fs1/home/b/bengioy/zhuzhaoc/torchdrug/torchdrug/tasks/task.py", line 30, in predict_and_target
    return self.predict(batch, all_loss, metric), self.target(batch)
  File "/gpfs/fs1/home/b/bengioy/zhuzhaoc/torchdrug/torchdrug/tasks/reasoning.py", line 137, in predict
    t_pred = self.model(self.fact_graph, h_index, t_index, r_index, all_loss=all_loss, metric=metric)
  File "/home/b/bengioy/zhuzhaoc/.conda/envs/drug/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/b/bengioy/zhuzhaoc/nbfnet/nbfnet/model.py", line 149, in forward
    output = self.bellmanford(graph, h_index[:, 0], r_index[:, 0])
  File "/home/b/bengioy/zhuzhaoc/.conda/envs/drug/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/gpfs/fs1/home/b/bengioy/zhuzhaoc/torchdrug/torchdrug/utils/decorator.py", line 92, in wrapper
    result = forward(self, *args, **kwargs)
TypeError: 'BoundArguments' object is not callable
```

**Comment by KiddoZhu** [comment]
Fixed in 518a699
