### ISSUE TITLE
RuntimeError: shape mismatch: value tensor of shape [28] cannot be broadcast to indexing result of shape [0]

### ISSUE THREAD

**Issue by sleeper2173** [DeepGraphLearning/torchdrug#12]
I tried to run the code of Molecule Generation in the Tutorials.
```
from torchdrug import datasets, core, models, tasks
from torch import optim

dataset = datasets.ZINC250k("~/molecule-datasets/", kekulize=True,
                            node_feature="symbol")
model = models.RGCN(input_dim=dataset.node_feature_dim,
                    num_relation=dataset.num_bond_type,
                    hidden_dims=[256, 256, 256, 256], batch_norm=False)
task = tasks.GCPNGeneration(model, dataset.atom_types, max_edge_unroll=12,
                            max_node=38, criterion="nll")
optimizer = optim.Adam(task.parameters(), lr = 1e-3)
solver = core.Engine(task, dataset, None, None, optimizer,
                     gpus=(0,), batch_size=128, log_interval=10)
solver.train(num_epoch=1)
solver.save("gcpn_zinc250k_1epoch.pkl")
results = task.generate(num_sample=32, max_resample=5)
```
And I got the error.
```
Traceback (most recent call last):
  File "./test.py", line 18, in <module>
    results = task.generate(num_sample=32, max_resample=5)
  File "/home/foo/opt/anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad                     return func(*args, **kwargs)
  File "/home/foo/opt/anaconda3/lib/python3.7/site-packages/torchdrug-0.1.0-py3.7.egg/torchdrug/tasks/generation.py", line 1369, in generate
    new_graph = self._apply_action(graph, off_policy, max_resample, verbose=1)
  File "/home/foo/opt/anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/foo/opt/anaconda3/lib/python3.7/site-packages/torchdrug-0.1.0-py3.7.egg/torchdrug/tasks/generation.py", line 1248, in _apply_action
    bond_type[is_modified_edge] = edge_action[has_modified_edge]
RuntimeError: shape mismatch: value tensor of shape [28] cannot be broadcast to indexing result of shape [0]
```
My environment : torch==1.4.0 ,python==3.7.4, rdkit==2020.03.3
Thanks.

**Comment by shichence** [comment]
Hi,
I try out the same code for molecule generation (GCPN model) on Google colab [(Click me)](https://colab.research.google.com/drive/1JEMiMvSBuqCuzzREYpviNZZRVOYsgivA#scrollTo=f0j0CLW5yJTL), and it seems everything works well.

I notice that the error is caused by line 1248 in `torchdrug/tasks/generation.py`, and the line number is different from our official codes. https://github.com/DeepGraphLearning/torchdrug/blob/6151fa9c742ae1cdeb931ce7ce8e1b2a9a08081d/torchdrug/tasks/generation.py#L1248
Did you modify these codes? Can you provide your `generation.py` codes?

**Comment by sleeper2173** [comment]
Upgrading PyTorch from 1.4 to 1.5 has made the code work fine.
Thanks.
