### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by lilili-cmd** [DeepGraphLearning/torchdrug#133]
Hi,when I use torchdrug to load the pretrained ESM, an error occured ,just like I show below.could you please help me to fix it?Thanks!

the code I used in my file was:
>>> from torchdrug import models
>>> model = models.EvolutionaryScaleModeling('./')
21:17:32   Downloading https://dl.fbaipublicfiles.com/fair-esm/models/esm1b_t33_650M_UR50S.pt to ./esm1b_t33_650M_UR50S.pt
21:39:01   Downloading https://dl.fbaipublicfiles.com/fair-esm/regression/esm1b_t33_650M_UR50S-contact-regression.pt to ./esm1b_t33_650M_UR50S-contact-regression.pt

and the error occured just like this.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/torchdrug/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/anaconda3/envs/torchdrug/lib/python3.7/site-packages/torchdrug-0.2.0-py3.7.egg/torchdrug/core/core.py", line 288, in wrapper
    return init(self, *args, **kwargs)
  File "/root/anaconda3/envs/torchdrug/lib/python3.7/site-packages/torchdrug-0.2.0-py3.7.egg/torchdrug/models/esm.py", line 55, in __init__
    _model, alphabet = self.load_weight(path, model)
  File "/root/anaconda3/envs/torchdrug/lib/python3.7/site-packages/torchdrug-0.2.0-py3.7.egg/torchdrug/models/esm.py", line 80, in load_weight
    return esm.pretrained.load_model_and_alphabet_core(model_data, regression_data)
  File "/root/anaconda3/envs/torchdrug/lib/python3.7/site-packages/esm/pretrained.py", line 190, in load_model_and_alphabet_core
    if model_name.startswith("esm2"):
AttributeError: 'dict' object has no attribute 'startswith'

**Comment by Oxer11** [comment]
Hi! Thanks for raising this issue.

This bug is because fair-esm has updated their interface when releasing ESM-2. I've fixed this issue in [180a9a8](https://github.com/DeepGraphLearning/torchdrug/commit/180a9a8b47fee6ab0e546db4406daf851b792c1d). You can solve this problem by either installing TorchDrug from the latest source code or downgrading fair-esm.

**Comment by lilili-cmd** [comment]
Thanks a lot! It's helpful!
