### ISSUE TITLE
UnboundLocalError: local variable 'sascorer' referenced before assignment in  Tutorials：Molecule Generation

### ISSUE THREAD

**Issue by Yongrui-Wang** [DeepGraphLearning/torchdrug#18]
HI，When I run to this part  "Goal-Directed Molecule Generation with Reinforcement Learning: GCPN"

```
import torch
import pickle
from torchdrug import core, datasets, models, tasks
from torch import nn, optim
from collections import defaultdict

with open("/home/ibmc-2/Projects/torchdrug/zinc250k.pkl", "rb") as fin:
    dataset = pickle.load(fin)

model = models.RGCN(input_dim=dataset.node_feature_dim,
                    num_relation=dataset.num_bond_type,
                    hidden_dims=[256, 256, 256, 256], batch_norm=False)
task = tasks.GCPNGeneration(model, dataset.atom_types,
                            max_edge_unroll=12, max_node=38,
                            task="plogp", criterion="ppo",
                            reward_temperature=1,
                            agent_update_interval=3, gamma=0.9)


optimizer = optim.Adam(task.parameters(), lr=1e-5)
solver = core.Engine(task, dataset, None, None, optimizer,
                     gpus=(0,), batch_size=16, log_interval=10)

solver.load("/home/ibmc-2/Projects/torchdrug/gcpn_zinc250k_1epoch.pkl",
             load_optimizer=False)

```
The above part works normally，but an error is reported when running to fine-tuning 
```
solver.train(num_epoch=10)
solver.save("/home/ibmc-2/Projects/torchdrug/gcpn_zinc250k_1epoch_finetune.pkl")
```
as follow
```
solver.train(num_epoch=10)
19:16:03   >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
19:16:03   Epoch 0 begin
/home/ibmc-2/anaconda3/envs/td/lib/python3.8/site-packages/torchdrug-0.1.0-py3.8.egg/torchdrug/data/molecule.py:103: UserWarning: Try to apply masks on molecules with stereo bonds. This may produce invalid molecules. To discard stereo information, call `mol.bond_stereo[:] = 0` before applying masks.
  warnings.warn("Try to apply masks on molecules with stereo bonds. This may produce invalid molecules. "
/home/ibmc-2/anaconda3/envs/td/lib/python3.8/site-packages/torch/nn/functional.py:1698: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
Traceback (most recent call last):
  File "/home/ibmc-2/anaconda3/envs/td/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-451bfe7c53dc>", line 1, in <module>
    solver.train(num_epoch=10)
  File "/home/ibmc-2/anaconda3/envs/td/lib/python3.8/site-packages/torchdrug-0.1.0-py3.8.egg/torchdrug/core/engine.py", line 143, in train
    loss, metric = model(batch)
  File "/home/ibmc-2/anaconda3/envs/td/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ibmc-2/anaconda3/envs/td/lib/python3.8/site-packages/torchdrug-0.1.0-py3.8.egg/torchdrug/tasks/generation.py", line 702, in forward
    _loss, _metric = self.reinforce_forward(batch)
  File "/home/ibmc-2/anaconda3/envs/td/lib/python3.8/site-packages/torchdrug-0.1.0-py3.8.egg/torchdrug/tasks/generation.py", line 813, in reinforce_forward
    plogp = metrics.penalized_logP(graph)
  File "/home/ibmc-2/anaconda3/envs/td/lib/python3.8/site-packages/torchdrug-0.1.0-py3.8.egg/torchdrug/metrics/metric.py", line 119, in penalized_logP
    #sa = sascorer.calculateScore(mol)
UnboundLocalError: local variable 'sascorer' referenced before assignment
```

By the way, is it normal that UserWarning: Unknown value `Tl` or `Mn` or `Cr` appears when downloading the ClinTox data set, thank you！

**Comment by yrq3027** [comment]
Thanks! The code running!
