### ISSUE TITLE
Unable to load `EnzymeCommissions`

### ISSUE THREAD

**Issue by jasperhyp** [DeepGraphLearning/torchdrug#182]
PyTorch version: `1.13.1+cu117`
RDKit version: `rdkit-2022.9.5-cp38`
Python version: `3.8.13`

Code:
```python
import torch
from torchdrug.datasets import EnzymeCommission
dataset = EnzymeCommission('./')
```
Log:
```
Constructing proteins from pdbs:   0%|                                                                                                                                   | 18/19198 [00:03<56:11,  5.69it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yeh803/.conda/envs/kg/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/yeh803/.conda/envs/kg/lib/python3.8/site-packages/torchdrug/core/core.py", line 288, in wrapper
    return init(self, *args, **kwargs)
  File "/home/yeh803/.conda/envs/kg/lib/python3.8/site-packages/torchdrug/datasets/enzyme_commission.py", line 66, in __init__
    self.load_pdbs(pdb_files, verbose=verbose, **kwargs)
  File "/home/yeh803/.conda/envs/kg/lib/python3.8/site-packages/torchdrug/data/dataset.py", line 750, in load_pdbs
    protein = data.Protein.from_molecule(mol, **kwargs)
  File "/home/yeh803/.conda/envs/kg/lib/python3.8/site-packages/torchdrug/utils/decorator.py", line 192, in wrapper
    return obj(*args, **kwargs)
  File "/home/yeh803/.conda/envs/kg/lib/python3.8/site-packages/torchdrug/data/protein.py", line 185, in from_molecule
    protein = Molecule.from_molecule(mol, atom_feature=atom_feature, bond_feature=bond_feature,
  File "/home/yeh803/.conda/envs/kg/lib/python3.8/site-packages/torchdrug/utils/decorator.py", line 192, in wrapper
    return obj(*args, **kwargs)
  File "/home/yeh803/.conda/envs/kg/lib/python3.8/site-packages/torchdrug/data/molecule.py", line 189, in from_molecule
    feature += func(atom)
  File "/home/yeh803/.conda/envs/kg/lib/python3.8/site-packages/torchdrug/data/feature.py", line 77, in atom_default
    onehot(atom.GetChiralTag(), chiral_tag_vocab) + \
  File "/home/yeh803/.conda/envs/kg/lib/python3.8/site-packages/torchdrug/data/feature.py", line 47, in onehot
    raise ValueError("Unknown value `%s`. Available vocabulary is `%s`" % (x, vocab))
ValueError: Unknown value `CHI_SQUAREPLANAR`. Available vocabulary is `range(0, 4)`
```

**Comment by Oxer11** [comment]
Hi, could you try with rdkit version `2022.09.1` installed from conda-forge? I think this is probably because rdkit identifies wrong bond in pdb files.

**Comment by jasperhyp** [comment]
I tried conda-forge and it installed `rdkit` instead of `rdkit-pypi`.  When installing torchdrug, another `rdkit-pypi` is automatically installed.  This one is the one specified above, which doesn't work.  After installing the newly installed `rdkit-pypi`, the `rdkit` from conda-forge cannot be recognized.

**Comment by KiddoZhu** [comment]
Hi! This is a legacy problem of pypi repositories. I just noticed that `pip install rdkit` now supports the same latest version as `pip install rdkit-pypi`. We should update the dependency to reduce conflicts in RDKit installation.

Could you try to clone TorchDrug, modify `rdkit-pypi` to `rdkit` in setup.py and then run `python setup.py install`?

**Comment by jasperhyp** [comment]
Seems to work, Thank you!
