### ISSUE TITLE
Which commit changed the default node dimension increased from 66 to 67?

### ISSUE THREAD

**Issue by jasperhyp** [DeepGraphLearning/torchdrug#191]
Hi!  For compatibility purposes, could you kindly let me know which commit changed the `default` node dimension from 66 to 67 using `Molecule` or `PackedMolecule`?  Or could you point me to the specific index in the node feature vector that I should remove in order to stay consistent with the previous default?  Thanks!

**Comment by Oxer11** [comment]
Hi, could you please provide the two versions of torchdrug that you find the default node dimensions are different? This will help us debug. Thanks~

BTW, there is a small modifcation in atom features in 36832c6 to remove time-consuming atom features. But this will only reduce the number of features.

**Comment by jasperhyp** [comment]
So I don't really remember what version it was but I created a `PackedMolecule` object at the start of this year.  After using the newest torchdrug to again pack some other molecules and pretrain a model, when finetuning the model using the previous molecules, I got this error:
```python
Traceback (most recent call last):
  File "train_torchdrug.py", line 331, in <module>
    preds = model(mol_graphs, head_indices, tail_indices, labels)
  File "/home/.conda/envs/primekg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "train_torchdrug.py", line 265, in forward
    z_mols = self.mol_encoder(mols, mols.node_feature.float())
  File "/home/.conda/envs/primekg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/.conda/envs/primekg/lib/python3.8/site-packages/torchdrug-0.2.0-py3.8.egg/torchdrug/models/gin.py", line 76, in forward
    hidden = layer(graph, layer_input)
  File "/home/.conda/envs/primekg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/.conda/envs/primekg/lib/python3.8/site-packages/torchdrug-0.2.0-py3.8.egg/torchdrug/layers/conv.py", line 91, in forward
    update = self.message_and_aggregate(graph, input)
  File "/home/.conda/envs/primekg/lib/python3.8/site-packages/torchdrug-0.2.0-py3.8.egg/torchdrug/layers/conv.py", line 346, in message_and_aggregate
    update += edge_update
RuntimeError: The size of tensor a (66) must match the size of tensor b (67) at non-singleton dimension 1
```

**Comment by Oxer11** [comment]
@KiddoZhu Do you have any idea about this problem?

**Comment by neurowelt** [comment]
@jasperhyp I built from the same commit and I redownloaded the ClinTox dataset, now `dataset.node_feature_dim == 66`.

In the meantime I did some additional digging in the `from_molecule` function which pointed me towards these lines:
https://github.com/DeepGraphLearning/torchdrug/blob/a959f68f0c19f368be9e380f5a587de6970b3c67/torchdrug/data/molecule.py#L187-L189

If I understand correctly, these functions will depend on taks types (property prediciton, synthons, center id.), but all of them are located [in feature.py](https://github.com/DeepGraphLearning/torchdrug/blob/master/torchdrug/data/feature.py), so if any shape is in some way different, perhaps some of the commits made on that file can explain that.

On the other hand, after I built the version you suggested, the redownloaded ClinTox shape change to 66 and I no longer had this issue.

The code below:
```python
import rdkit
import torchdrug
print(rdkit.__version__)
print(torchdrug.__version__)

mol = data.Molecule.from_smiles('C')
print(mol.atom_feature.shape[1])

with open("./ClinTox.pkl", "rb") as fin:
    clintox = pickle.load(fin)
print(clintox.data[0].atom_feature.shape[1])
```

Outputs:
```shell
2021.09.4
0.2.0
66
66
```

That's what I got so far, I'll let know if I find something more.

**Comment by jasperhyp** [comment]
Ok then the problem must be `rdkit`??
```python
import rdkit
from torchdrug import data
print(rdkit.__version__)
print(torchdrug.__version__)

mol = data.Molecule.from_smiles('C')
print(mol.atom_feature.shape[1])
```
Outputs:
```
2022.09.5
0.2.0
67
```

**Comment by neurowelt** [comment]
I think we got it 😊 I kind of suspected that. I remember #170 , I reinstalled `rdkit` for that reason, but later on I also remember checking out `pip show rdkit-pypi` and getting `2022.*.*` version. I think I just got them twisted and trained something in one version, tried opening in a different one.

Seems like it's `rdkit` version problem, not `torchdrug`.

**Comment by jasperhyp** [comment]
interesting, maybe it would be good to have an assertion in the feature generator! @Oxer11

**Comment by AH-Merii** [comment]
This means that anyone trying to follow the pretraining and finetuning tutorials won't be able to implement them, as the models expect an input dimension of 21. When using `atom_feature="pretrain"`, with the newer version of rdkit it yeilds an input demension of 22 instead of 21.

**Comment by AH-Merii** [comment]
So I did a bit of investigating and the reason I am getting 22 instead of 21 has nothing to do with the version of rdkit. Is because `allow_unknown=True` in  `onehot(atom.GetSymbol(), atom_vocab, allow_unknown=True)` in the snippet below.

```python
@R.register("features.atom.pretrain")
def atom_pretrain(atom):
    """Atom feature for pretraining.

    Features:
        GetSymbol(): one-hot embedding for the atomic symbol
        
        GetChiralTag(): one-hot embedding for atomic chiral tag
    """
    return onehot(atom.GetSymbol(), atom_vocab, allow_unknown=True) + \
           onehot(atom.GetChiralTag(), chiral_tag_vocab)
```

When I changed the value to False, I was able get 21 instead of 22.
