### ISSUE TITLE
Shape invalid in GearNet, GeometricRelationalGraphConv.message_and_aggregate()

### ISSUE THREAD

**Issue by Chris-Tang6** [DeepGraphLearning/torchdrug#200]
Hello🤗, I was running my customized classification dataset based on GearNet.
I run the code in Ubuntu, python38, torch1.8, torchdrug0.2.0.
But it had runtime error: 
```
Traceback (most recent call last):
  File "./test.py", line 106, in <module>
    solver.train(num_epoch=10)
  File "/homeb/tangwuguo/miniconda3/envs/cbc23/lib/python3.8/site-packages/torchdrug/core/engine.py", line 155, in train
    loss, metric = model(batch)
  File "/homeb/tangwuguo/miniconda3/envs/cbc23/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/homeb/tangwuguo/miniconda3/envs/cbc23/lib/python3.8/site-packages/torchdrug/tasks/property_prediction.py", line 96, in forward
    pred = self.predict(batch, all_loss, metric)
  File "/homeb/tangwuguo/miniconda3/envs/cbc23/lib/python3.8/site-packages/torchdrug/tasks/property_prediction.py", line 134, in predict
    output = self.model(graph, graph.node_feature.float(), all_loss=all_loss, metric=metric)
  File "/homeb/tangwuguo/miniconda3/envs/cbc23/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/homeb/tangwuguo/miniconda3/envs/cbc23/lib/python3.8/site-packages/torchdrug/models/gearnet.py", line 95, in forward
    hidden = self.layers[i](graph, layer_input)
  File "/homeb/tangwuguo/miniconda3/envs/cbc23/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/homeb/tangwuguo/miniconda3/envs/cbc23/lib/python3.8/site-packages/torchdrug/layers/conv.py", line 91, in forward
    update = self.message_and_aggregate(graph, input)
  File "/homeb/tangwuguo/miniconda3/envs/cbc23/lib/python3.8/site-packages/torchdrug/layers/conv.py", line 813, in message_and_aggregate
    return update.view(graph.num_node, self.num_relation * self.input_dim)
RuntimeError: shape '[449, 147]' is invalid for input of size 207438
```

## The customized dataset
```
class ScopeSuperFamilyClassify(data.ProteinDataset):
    source_file = "pdb_scope_db40.csv"
    pdb_dir = "dbstyle_all-40-2.08"
    processed_file = 'scope_superfamily.pkl.gz'

    label2id_dir = 'pdb_scope_label2id.pkl'
    id2label_dir = 'pdb_scope_id2label.pkl'
    
    splits = ["train", "valid","test"]
    split_ratio = [0.8, 0.1]
    target_fields = ["superfamily_label"]  # label column

    def __init__(self, path='/home/tangwuguo/datasets/scope40', verbose=1, **kwargs):
        if not os.path.exists(path):
            raise FileExistsError("Unknown path `%s` for SCOPE dataset" % path)
        self.path = path            
        df = pd.read_csv(os.path.join(path, self.source_file))
        pkl_file = os.path.join(path, self.processed_file)
        
        if os.path.exists(pkl_file):  
            # load processed pkl
            self.load_pickle(pkl_file, verbose=verbose, **kwargs)
        else:            
            pdb_files = df['id']
            pdb_files = pdb_files.apply(lambda x: os.path.join(path, self.pdb_dir, x+'.ent')).tolist()
            self.load_pdbs(pdb_files=pdb_files, verbose=1)
            self.save_pickle(pkl_file, verbose=verbose)
                    
        len = df['id'].size
        train_size = int(len*self.split_ratio[0])
        valid_size = int(len*self.split_ratio[1])
        test_size = len - train_size - valid_size
        self.num_samples = [train_size, valid_size, test_size]
        self.targets = {'superfamily_label': torch.tensor(df['label'].tolist())}
    
    
    def split(self, keys=None):
        keys = keys or self.splits
        offset = 0
        splits = []
        for split_name, num_sample in zip(self.splits, self.num_samples):
            if split_name in keys:
                split = torch_data.Subset(self, range(offset, offset + num_sample))
                splits.append(split)
            offset += num_sample
        return splits
        
    
    def get_item(self, index):
        if self.lazy:
            protein = self.load_hdf5(self.pdb_files[index])
        else:
            protein = self.data[index].clone()
        if hasattr(protein, "residue_feature"):
            with protein.residue():
                protein.residue_feature = protein.residue_feature.to_dense()
        item = {"graph": protein, "superfamily_label": self.targets["superfamily_label"][index]}
        if self.transform:
            item = self.transform(item)
        return item
```
 ## Some info about the protein graph
```
print(protein_.atom_feature[0].shape)
print(protein_.residue_feature[0].shape)
print(protein_.edge_feature[0].shape)
print(protein_.num_node)
print(protein_.num_relation)
print(protein_.adjacency)
_________________________________________
torch.Size([66])
torch.Size([21])
torch.Size([59])
tensor(327)
tensor(7)
tensor(indices=tensor([[232, 230, 163,  ..., 216, 217, 215],
                       [193, 195, 194,  ..., 210, 210, 210],
                       [  1,   1,   1,  ...,   0,   0,   0]]),
       values=tensor([1., 1., 1.,  ..., 1., 1., 1.]),
       size=(327, 327, 7), nnz=6657, layout=torch.sparse_coo)
```

## The running code
```
gearnet = models.GearNet(input_dim=21, hidden_dims=[512, 512, 512], num_relation=7,
                         batch_norm=True, concat_hidden=True, short_cut=True, readout="sum")

graph_construction_model = layers.GraphConstruction(node_layers=[geometry.AlphaCarbonNode()],
                                                    edge_layers=[geometry.SpatialEdge(radius=10.0, min_distance=5),
                                                                 geometry.KNNEdge(k=10, min_distance=5),
                                                                 geometry.SequentialEdge(max_distance=2)],
                                                    edge_feature="gearnet")

task = tasks.PropertyPrediction(gearnet, graph_construction_model=graph_construction_model, num_mlp_layer=3, 
                                          task=dataset.tasks, num_class=2065, criterion="ce", metric=["auprc", "auroc", "f1_max"])

optimizer = torch.optim.Adam(task.parameters(), lr=1e-4)
solver = core.Engine(task, train_set, valid_set, test_set, optimizer,
                     gpus=[1], batch_size=4)
solver.train(num_epoch=10)

```

**Comment by Chris-Tang6** [comment]
Sorry, I have found the bug. I forgot to use the transforms on my dataset. 

```
truncate_transform = transforms.TruncateProtein(max_length=350, random=False)
protein_view_transform = transforms.ProteinView(view="residue")
transform = transforms.Compose([truncate_transform, protein_view_transform])

start_time = time.time()
dataset = ScopeSuperFamilyClassify("/home/tangwuguo/datasets/scope40", transform=transform)
end_time = time.time()
print("Duration of second instantiation: ", end_time - start_time)
```
