### ISSUE TITLE
FAILED: spmm.cuda.o FAILED: rspmm.cuda.o

### ISSUE THREAD

**Issue by boxorange** [DeepGraphLearning/torchdrug#216]
Hi, 
I got the following error. Can you help resolve the issue?
Here're the packages I'm using. The gpus are A100.
```
torch==2.0.1+cu118
torch-cluster==1.6.1+pt20cu118
torch-scatter==2.1.1+pt20cu118
torch-sparse==0.6.17+pt20cu118
torchdrug==0.2.1
```
The error message is:
```
Original exception was:
Traceback (most recent call last):
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "script/run.py", line 58, in <module>
    solver = util.build_solver(cfg, dataset)
  File "/home/ac.gpark/AStarNet/reasoning/util.py", line 105, in build_solver
    task = core.Configurable.load_config_dict(cfg.task)
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torchdrug/core/core.py", line 269, in load_config_dict
    v = _Configurable.load_config_dict(v)
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torchdrug/core/core.py", line 269, in load_config_dict
    v = _Configurable.load_config_dict(v)
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torchdrug/core/core.py", line 277, in load_config_dict
    return cls(**new_config)
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torchdrug/core/core.py", line 296, in wrapper
    return init(self, *args, **kwargs)
  File "/home/ac.gpark/AStarNet/reasoning/layer.py", line 55, in __init__
    functional.generalized_rspmm(adjacency, relation_input, input, sum="add", mul="mul")
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torchdrug/layers/functional/spmm.py", line 378, in generalized_rspmm
    return Function.apply(sparse.coalesce(), relation, input)
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torchdrug/layers/functional/spmm.py", line 174, in forward
    forward = spmm.rspmm_add_mul_forward_cpu
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torchdrug/utils/torch.py", line 26, in __getattr__
    return getattr(self.module, key)
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torchdrug/utils/decorator.py", line 102, in __get__
    result = self.func(obj)
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torchdrug/utils/torch.py", line 30, in module
    return cpp_extension.load(self.name, self.sources, self.extra_cflags, self.extra_cuda_cflags,
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'spmm': [1/3] /home/ac.gpark/anaconda3/pkgs/cuda-12.1.0-0/bin/nvcc  -ccbin /home/ac.gpark/anaconda3/envs/gnn/bin/x86_64-conda_cos6-linux-gnu-cc -DTORCH_EXTENSION_NAME=spmm -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include/TH -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include/THC -isystem /home/ac.gpark/anaconda3/pkgs/cuda-12.1.0-0/include -isystem /home/ac.gpark/anaconda3/envs/gnn/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -std=c++17 -c /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torchdrug/layers/functional/extension/spmm.cu -o spmm.cuda.o
FAILED: spmm.cuda.o
/home/ac.gpark/anaconda3/pkgs/cuda-12.1.0-0/bin/nvcc  -ccbin /home/ac.gpark/anaconda3/envs/gnn/bin/x86_64-conda_cos6-linux-gnu-cc -DTORCH_EXTENSION_NAME=spmm -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include/TH -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include/THC -isystem /home/ac.gpark/anaconda3/pkgs/cuda-12.1.0-0/include -isystem /home/ac.gpark/anaconda3/envs/gnn/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -std=c++17 -c /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torchdrug/layers/functional/extension/spmm.cu -o spmm.cuda.o
/bin/sh: 1: /home/ac.gpark/anaconda3/pkgs/cuda-12.1.0-0/bin/nvcc: not found
[2/3] /home/ac.gpark/anaconda3/pkgs/cuda-12.1.0-0/bin/nvcc  -ccbin /home/ac.gpark/anaconda3/envs/gnn/bin/x86_64-conda_cos6-linux-gnu-cc -DTORCH_EXTENSION_NAME=spmm -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include/TH -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include/THC -isystem /home/ac.gpark/anaconda3/pkgs/cuda-12.1.0-0/include -isystem /home/ac.gpark/anaconda3/envs/gnn/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -std=c++17 -c /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torchdrug/layers/functional/extension/rspmm.cu -o rspmm.cuda.o
FAILED: rspmm.cuda.o
/home/ac.gpark/anaconda3/pkgs/cuda-12.1.0-0/bin/nvcc  -ccbin /home/ac.gpark/anaconda3/envs/gnn/bin/x86_64-conda_cos6-linux-gnu-cc -DTORCH_EXTENSION_NAME=spmm -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include/TH -isystem /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torch/include/THC -isystem /home/ac.gpark/anaconda3/pkgs/cuda-12.1.0-0/include -isystem /home/ac.gpark/anaconda3/envs/gnn/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -std=c++17 -c /home/ac.gpark/anaconda3/envs/gnn/lib/python3.8/site-packages/torchdrug/layers/functional/extension/rspmm.cu -o rspmm.cuda.o
/bin/sh: 1: /home/ac.gpark/anaconda3/pkgs/cuda-12.1.0-0/bin/nvcc: not found
ninja: build stopped: subcommand failed.
```

**Comment by KiddoZhu** [comment]
Hi! `nvcc` is the compiler for CUDA programs. How did you install your `cudatoolkit`?

**Comment by boxorange** [comment]
I installed ```cudatoolkit``` with these commands ```conda install -c nvidia cuda```, and ```conda install cudatoolkit```. I set the paths like this ```export CUDA_HOME=/home/ac.gpark/anaconda3/pkgs/cuda-12.1.0-0```,
```export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ac.gpark/anaconda3/pkgs/cuda-cudart-12.1.55-0/lib```.
When I run the test code in torchdrug github, it works fine. The error occurs when I run A\*Net (https://github.com/DeepGraphLearning/AStarNet). Since the error message is about torchdrug, I posted the issue here. Can the issue be in A\*Net?

**Comment by boxorange** [comment]
It was a cudatoolkit installation issue. When it was installed at a system level rather than my conda env, it's working well. Thanks for your help!

**Comment by EauDeData** [comment]
Hi, sorry for openning again, but I've been running through the same issue when running AStartNet. 
I install the dependencies as follow, from a py3.10 fresh new conda environment
`pip install numpy==1.26.4
pip install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu124
pip install torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-2.4.0+cu124.html
pip install torch-cluster -f https://data.pyg.org/whl/torch-2.4.0+cu124.html
pip install pyg-lib -f https://data.pyg.org/whl/torch-2.4.0+cu124.html
pip install torchdrug

pip install ogb
pip install easydict
pip install PyYAML
pip install easydict`

However, after running the basic command `CUDA_VISIBLE_DEVICES=0 python script/run.py -c config/transductive/fb15k237_astarnet.yaml --gpus 0`

Torchdrug raises the following error message: `fatal error: ATen/SparseTensorUtils.h: No such file or directory`. Which is a sad but true; however, I don't know what else to try and install and play around multiple dependencies to solve it. 

Is it similar in a way from what you did experience?
Thanks
